sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_script:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install
  - npm install -g xo
  - npm install -g snyk
  - gulp build
  - gulp examples:build
script:
  - npm test
  - npm run deploy
after_success:
  - nyc --reporter=lcov ava
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
  - rm -rf ./nyc_output
