sudo: required
dist: trusty
language: node_js
os: osx
node_js:
  - "6"
before_script:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install
  - gulp build
  - gulp examples:build
script:
  - npm test
after_success:
  - npm run deploy
  - jest --coverage
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
