language: node_js
node_js:
  - "6"
before_script:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp src:test
branches:
  only:
    - master
