sudo: required
dist: trusty
language: node_js
os: linux
sudo: required
dist: trusty
group: deprecated-2017Q2
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
node_js:
  - "6"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install
  - npm run build
script:
  - npm test
after_success:
  - jest --coverage
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
before_deploy:
  - gulp examples:build
deploy:
  provider: surge
  project: ./
  domain: whs-dev.surge.sh
  skip_cleanup: true
  on: dev
deploy:
  provider: npm
  email: "hirako2000@gmail.com"
  api_key:
  secure: "xwzTnaLZgnUQtYUcwZozGKygC3Qxe34uW9+b/vWmq1bVQQye7llbt7ttgwvCc+s6Kx5twJhL2YpN6b1oHno9wg7gKHaKUhorNnSe7faKM8H+uSLabdm0YQogfehBxfaJjuUwtCDJkizNdbxovJhLpZk4OHZxK//M0FjaL0b97rgK/E6fNjaVE8/EDb1k6tvtt4o+n8CqTtBCFOFsm1TUJsEPwiek9mieZjN5sc6BW3oyJfI65f0NGBr0szxkOfk/gYJK+f/sYMfrdbMvnILDS9Jup4hdWF3ttJnaHaezFmqqfMqK8L7V7sc5x52YWm7C0ewECpzAJQL7QwRpfl7k+tNJHTZMsfmxq70WUEmr9KhTISqoXMFP0RY7gCQ1s3EtAVsPD+vqlsrB1DZNBUb2mNUm0NuIZNwWaTjjMUTqvPMma6fGj5/753e2kgomcPds+Gu/e8/rylGxGtcjy186+lNCyRysoZmX079CkaYK8LI4wjoUTvUTcy6Ai8wXb/drBJ+F+kDgelZY6jxE2t6ASCax4daKrdtaRECxqyW0cbucU8qlgsHYPlTvpDa+8T1cYd5gIcNGlJd6K7CO8FGSc3dFdBGQ4jXsQMJXz7PK26SGFyM5sP2BCQlByi+Rx1HSdOZ3c7A9G7wFM33yzPz+DnaGAbD8qiQXN3ci3k03HqE="
  on:
    branch: dev
    tags: true
